name: python-tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pytest-cov

      - name: Black (format check)
        run: black --check .

      - name: Flake8 (lint)
        run: flake8

      - name: Pytest (with coverage)
        run: pytest --cov=src --cov-report=term-missing -q

      - name: Save artifacts
        if: always()
        run: |
          pytest --cov=src --cov-report=xml:coverage.xml || true
          python -m src.stock_analysis_cli --ticker AAPL --start 2020-01-01 --end 2025-01-01 > cli_output.json || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            coverage.xml
            cli_output.json
